<script lang="ts">
	import { BadgeCheck, BriefcaseBusiness, GraduationCap, Mail, ExternalLink, MapPin, Trophy } from '@lucide/svelte';

	const summaryParagraphs = [
		"I'm at my best when I can get to know people and their processes thoroughly so I can help them solve problems or discover opportunities. I function well in a team thanks to my experience in most project management processes and tools as they evolved with me throughout my career.",
		"Working in varied industries of mixed sizes has shown me when to focus on being fast and self-steering as well as how to function in highly connected teams and manage complex SLAs and project planning. My most recent achievements involved working with an international team to scale up iChoosr's group buying software to match the company's rapid growth.",
		"We moved from a self-hosted Ruby on Rails application to a fully scalable, easy to manage suite on Azure. We supported customer-facing and back-office portals as well as various third-party integrations, and we grew to support complex localizations, agile product diversification, and steep concurrent load growth. You can ask me anything about C#, SQL, Entity Framework, HTML, TypeScript, vertical slicing, C4 diagrams, the culture map, SvelteKit, or my home lab."
	];

	const workExperience = [
		{
			period: '2023-01 - 2025-12',
			title: 'Principal Engineer',
			company: 'iChoosr',
			description:
				'At iChoosr I had an amazing time bringing the New Horizons platform live and scaling it up. I learned to really appreciate the highly rewarding, fast-paced start-up environment, got familiar with Azure. As a principal engineer, I had the chance to steer the platform in its final iteration and draw the first lines for its successor.'
		},
		{
			period: '2020-04 - 2022-12',
			title: 'Technical Lead',
			company: 'iChoosr',
			description: 'Was selected as Technical Lead representing the Belgium team. Together with the Dutch and Polish ones we gathered periodically to tackle overarching problems that became apparent now the software was slowly maturing. We extracted satellite APIs based on the same domains as the team structure was set up. We extended the platform with another UI and set up various integrations with our external suppliers and communities.'
		},
		{
			period: '2018-11 - 2020-04',
			title: 'Full-stack Developer',
			company: 'iChoosr',
			description: 'Helped building out the new platform in an international team. In a team of full stack developers we all were dispersed amongst our business users and support employees to discover the right features and bring them forward for analysis, planning, development and finally deployment. We created a central monolithic API and used it for the three different frontends for various user groups both internal and external.'
		},
		{
			period: '2013-12 - 2018-11',
			title: 'Senior .net developer',
			company: 'SD Worx',
			description:
				'Responsible for development after the initial setup of the Flex Income Plan proof of concept. Supported technical operations and provided last line user support. Later helped in the team responsible for the MyWorkAndMe platform and helped embedding the legacy C++ XBlox application into an ASP.net MVC website. I learned the reality of old code bases, multi-tenancy, SQL performance work, and the opportunities with containerized environments.'
		},
		{
			period: '2012-01 - 2012-12',
			title: 'Co-founder',
			company: 'Bojojoing',
			description: 'We created a simple website for a real estate initiative next to Berchem Station. My friend and I needed a VAT number.'
		},
		{
			period: '2007-01 - 2010-08',
			title: 'Jr. .NET Developer',
			company: 'Coteng',
			description: 'My first serious solo .NET programming project taught me a lot through self-study and iteration. I built a website in ASP.net MVC 1.0 that could stream in lots of color swatches generated by a proprietary COM object and learned using Lucene for fast search.'
		},
		{
			period: '2007-06 - 2007-10',
			title: 'Jr. Internal Development and Technical Support EMEA',
			company: 'FedEx',
			description: 'Internal development and technical support with a migration from MQ to JMS technology.'
		}
	];

	const education = [
		{
			period: '2006-01',
			title: 'Bachelor of Applied Informatics',
			institution: 'Hogeschool Antwerpen',
			description: 'Applied Informatics (2004 - 2006)'
		},
		{
			period: '1998-01',
			title: '',
			institution: 'Xaverius College Borgerhout',
			description: 'Lecture & expressiveness, Drama and Dramatics/Theatre Arts, General (1992 - 1998)'
		}
	];

	const qualifications = ['Software Infrastructure', 'Software Systems Engineering', 'Software Design'];
	const achievements = ['Worked with an international team to scale a platform during rapid growth.'];
</script>

<svelte:head>
	<title>Resume | Boris Callens</title>
	<meta
		name="description"
		content="Resume page for Boris Callens. A software engineer who likes creating software that people love to use."
	/>
</svelte:head>

<section class="resume-page" aria-label="Resume for Boris Callens">
	<aside class="sidebar" aria-label="Profile and summary">
		<div class="profile-card">
			<div class="portrait-ring">
				<img class="portrait" src="/portrait.jpg" alt="Portrait of Boris Callens" />
			</div>
			<div class="identity">
				<h1>Boris Callens</h1>
				<p class="location">
					<MapPin class="location-icon" aria-hidden="true" size={16} strokeWidth={2} />
					Historical Center of Antwerp, BE
				</p>
				<a class="contact-link" href="mailto:boris.callens+linkedin@gmail.com">
					<Mail class="contact-icon" aria-hidden="true" size={16} strokeWidth={2} />
					boris.callens+linkedin@gmail.com
				</a>
				<a class="contact-link" href="https://www.linkedin.com/in/boriscallens" target="_blank" rel="noreferrer">
					<ExternalLink class="contact-icon" aria-hidden="true" size={16} strokeWidth={2} />
					www.linkedin.com/in/boriscallens
				</a>
			</div>
		</div>
		<div class="summary-card">
			<h2>Summary</h2>

			{#each summaryParagraphs as paragraph (paragraph)}
				<p>{paragraph}</p>
			{/each}
		</div>
	</aside>

	<div class="detail-stack">
		<article class="resume-section">
			<header class="resume-header">
				<BriefcaseBusiness class="section-icon" aria-hidden="true" size={18} strokeWidth={2} />
				<h2>Work experience</h2>
			</header>

			<div class="entries">
				{#each workExperience as experience (experience.period)}
					<article class="entry">
						<p class="period">{experience.period}</p>
						<h3>{experience.title}</h3>
						<p class="company">{experience.company}</p>
						<span class="description">{experience.description}</span>
					</article>
				{/each}
			</div>
		</article>

		<article class="resume-section">
			<header class="resume-header">
				<GraduationCap class="section-icon" aria-hidden="true" size={18} strokeWidth={2} />
				<h2>Education</h2>
			</header>

			<div class="entries compact-entries">
				{#each education as item (item.period)}
					<article class="entry compact-entry">
						<p class="period">{item.period}</p>
						{#if item.title}
							<h3>{item.title}</h3>
						{/if}
						<p class="company">{item.institution}</p>
						<span class="description">{item.description}</span>
					</article>
				{/each}
			</div>
		</article>

		<!-- <article class="resume-section split-section">
			<header class="resume-header">
				<BadgeCheck class="section-icon" aria-hidden="true" size={18} strokeWidth={2} />
				<h2>Qualifications</h2>
			</header>

			<ul class="chip-list">
				{#each qualifications as item (item)}
					<li>{item}</li>
				{/each}
			</ul>
		</article>

		<article class="resume-section split-section">
			<header class="resume-header">
				<Trophy class="section-icon" aria-hidden="true" size={18} strokeWidth={2} />
				<h2>Achievements</h2>
			</header>

			<ul class="bullets">
				{#each achievements as achievement (achievement)}
					<li>{achievement}</li>
				{/each}
			</ul>
		</article> -->
	</div>
</section>

<style>
	:global(body) {
		background:
			radial-gradient(circle at top left, rgba(121, 119, 158, 0.14), transparent 30%),
			linear-gradient(180deg, #f8f7fb 0%, #f5f4f8 100%);
	}

	@media print {
		@page {
			margin: 0.75in;
		}

		:global(body) {
			min-height: 100%;
			background: white !important;
			color: #000;
			font-size: 11pt;
			line-height: 1.5;
		}

		:global(header),
		:global(nav),
		:global(#signIn),
		:global(footer) {
			display: none !important;
			visibility: hidden !important;
			height: 0 !important;
		}

		.resume-page {
			width: 100%;
			margin: 0;
			padding: 0;
			grid-template-columns: 1fr;
			gap: 1rem;
			height: 90vh;
		}

		.sidebar {
			display: grid;
			grid-template-columns: minmax(0, 1.15fr) minmax(0, 1fr);
			gap: 1rem;
			align-items: start;
			break-after: page;
			page-break-after: always;
		}

		.detail-stack,
		.entries,
		.compact-entries,
		.chip-list,
		.bullets {
			gap: 0.75rem;
		}

		.sidebar {
			position: static;
		}

		.summary-card {
			align-self: start;
		}

		.detail-stack {
			break-before: page;
			page-break-before: always;
		}

		/* .profile-card,
		.summary-card,
		.resume-section {
			background: white;
			box-shadow: none;
			backdrop-filter: none;
		} */


		.profile-card,
		.summary-card,
		.detail-stack > article,
		.entry,
		.chip-list li,
		.bullets li {
			all: unset;
			break-inside: avoid;
			page-break-inside: avoid;
		}

		.resume-header,
		.entry {
			break-after: avoid;
			page-break-after: avoid;
		}

		.summary-card p,
		.description,
		.chip-list li,
		.bullets li {
			font-size: 10pt;
			line-height: 1.45;
		}

		.profile-card {
			min-height: auto;
			padding: 1rem;
			gap: 0.9rem;
		}

		.portrait-ring {
			width: 180px;
		}

		.resume-section {
			padding: 1rem 1.05rem;
		}

		.description {
			background: #f3f4f6;
			padding: 0.75rem 0.85rem;
		}
	}

	.resume-page {
		width: min(1280px, calc(100% - 2rem));
		margin: 0 auto;
		padding: 2rem 0 3rem;
		display: grid;
		grid-template-columns: minmax(280px, 330px) minmax(0, 1fr);
		gap: 2rem;
		align-items: start;
	}

	.sidebar {
		position: sticky;
		top: 1rem;
		display: grid;
		gap: 1.25rem;
	}

	.profile-card,
	.summary-card,
	.resume-section {
		background: rgba(255, 255, 255, 0.88);
		border: 1px solid rgba(115, 122, 145, 0.16);
		box-shadow: 0 10px 24px rgba(25, 31, 46, 0.05);
		backdrop-filter: blur(10px);
	}

	.profile-card {
		min-height: 350px;
		padding: 1.5rem 1.25rem 1.4rem;
		background: linear-gradient(180deg, #6f6882 0%, #686176 100%);
		color: white;
		display: grid;
		justify-items: center;
		align-content: start;
		gap: 1.25rem;
	}

	.portrait-ring {
		position: relative;
		width: 250px;
		aspect-ratio: 1;
		padding: 0.5rem;
		box-sizing: border-box;
		display: grid;
		place-items: center;
	}

	.portrait-ring::before {
		content: '';
		position: absolute;
		inset: 0;
		background: #fff;
		clip-path: polygon(50% 0%, 100% 25%, 100% 75%, 50% 100%, 0% 75%, 0% 25%);
	}

	.portrait {
		width: 100%;
		height: 100%;
		object-fit: cover;
		clip-path: polygon(50% 0%, 100% 25%, 100% 75%, 50% 100%, 0% 75%, 0% 25%);
	}

	.identity {
		display: grid;
		justify-items: center;
		gap: 0.55rem;
		text-align: center;
	}

	.contact-link {
		display: inline-flex;
		align-items: center;
		gap: 0.6rem;
		justify-self: start;
		text-decoration: none;
		color: inherit;
	}

	.identity h1 {
		margin: 0;
		font-size: clamp(2rem, 4vw, 2.75rem);
		line-height: 0.95;
		letter-spacing: -0.05em;
	}

	.identity p,
	.identity a {
		margin: 0;
		font-size: 0.95rem;
		color: inherit;
		text-decoration: none;
	}

	.location {
		display: inline-flex;
		align-items: center;
		gap: 0.55rem;
		justify-self: start;
		text-align: left;
	}

	.identity a:hover {
		text-decoration: underline;
	}

	.summary-card {
		padding: 1.15rem 1.1rem 1.25rem;
		color: #313843;
	}

	.summary-card h2,
	.resume-header h2 {
		margin: 0;
		font-size: 1.05rem;
		letter-spacing: 0.03em;
	}

	.summary-card p {
		margin: 0.85rem 0 0;
		font-size: 0.95rem;
		line-height: 1.55;
		color: #51586a;
	}

	.detail-stack {
		display: grid;
		gap: 1.2rem;
	}

	.resume-section {
		padding: 1.15rem 1.2rem 1.2rem;
		border-radius: 0.9rem;
	}

	.resume-header {
		display: flex;
		align-items: center;
		gap: 0.7rem;
		padding-bottom: 0.75rem;
		border-bottom: 1px solid rgba(107, 120, 145, 0.2);
		margin-bottom: 1rem;
	}

	.entries {
		display: grid;
		gap: 1.1rem;
	}

	.entry {
		display: grid;
		grid-template-columns: auto minmax(0, 1fr) ;
		grid-template-areas:
			'period .'
			'title company'
			'description description';
		row-gap: 0.3rem;
	}

	.period {
		grid-area: period;
		margin: 0;
		font-size: 0.8rem;
		color: #7f8695;
	}

	.entry h3 {
		grid-area: title;
		margin: 0;
		font-size: 1.65rem;
		line-height: 1.08;
		font-weight: 600;
		letter-spacing: -0.03em;
		color: #1f2530;
	}

	.company {
		grid-area: company;
		margin: 0;
		font-size: 1rem;
		color: #ff6f61;
		justify-self: end;
		text-align: right;
		align-self: end;
	}

	.description {
		grid-area: description;
		display: block;
		margin: 0;
		background: rgba(242, 245, 249, 0.95);
		border-radius: 0.65rem;
		padding: 0.9rem 0.95rem;
		color: #596273;
		line-height: 1.55;
		font-size: 0.95rem;
	}

	.compact-entry h3 {
		font-size: 1.25rem;
	}

	.split-section {
		grid-template-columns: 1fr;
	}

	.chip-list,
	.bullets {
		margin: 0;
		padding: 0;
		list-style: none;
		display: grid;
		gap: 0.65rem;
	}

	.chip-list li,
	.bullets li {
		background: rgba(242, 245, 249, 0.95);
		border-radius: 0.65rem;
		padding: 0.85rem 0.95rem;
		color: #596273;
		line-height: 1.45;
	}

	@media (max-width: 960px) {
		.resume-page {
			width: min(100%, calc(100% - 1rem));
			grid-template-columns: 1fr;
		}

		.sidebar {
			position: static;
		}
	}

	@media (max-width: 640px) {
		.resume-page {
			width: min(100%, calc(100% - 0.75rem));
			padding-top: 0.75rem;
		}

		.profile-card {
			min-height: 0;
		}

		.entry h3 {
			font-size: 1.35rem;
		}

		.company {
			justify-self: start;
			text-align: left;
		}
	}
</style>
